[[build.buildpacks]]
uri = "heroku/nodejs"

[[build.buildpacks]]
uri = "heroku/ruby"

[[build.buildpacks]]
uri = "heroku/php"

[[build.buildpacks]]
uri = "heroku/python"

[[build.buildpacks]]
uri = "https://github.com/jkutner/heroku-buildpack-ngrok.git"